version: '3.9'
services:
  server:
    hostname: server
    build: ./server
    ports:
      - "8080:8080"
  client:
    build: ./client
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_LOCATION=http://localhost:8080
    depends_on:
      - server
